"""empty message

Revision ID: 3c0d4c10be75
Revises: 
Create Date: 2021-03-21 10:13:04.606685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0d4c10be75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_proper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('numOfBed', sa.String(length=80), nullable=True),
    sa.Column('numOfBath', sa.String(length=30), nullable=True),
    sa.Column('pric', sa.String(length=80), nullable=True),
    sa.Column('proptype', sa.String(length=29), nullable=True),
    sa.Column('location', sa.String(length=225), nullable=True),
    sa.Column('photo_name', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_proper_photo_name'), 'user_proper', ['photo_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_proper_photo_name'), table_name='user_proper')
    op.drop_table('user_proper')
    # ### end Alembic commands ###
