"""empty message

Revision ID: 6fd2ebd7d122
Revises: 
Create Date: 2021-03-21 14:35:25.437781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd2ebd7d122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_proper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('numOfBed', sa.INTEGER(), nullable=True),
    sa.Column('numOfBath', sa.INTEGER(), nullable=True),
    sa.Column('pric', sa.String(length=80), nullable=True),
    sa.Column('proptype', sa.String(length=29), nullable=True),
    sa.Column('location', sa.String(length=225), nullable=True),
    sa.Column('photo_name', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_proper')
    # ### end Alembic commands ###
