"""empty message

Revision ID: 763ecc7c6916
Revises: 
Create Date: 2021-03-15 18:50:45.564849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763ecc7c6916'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('numOfBed', sa.String(length=80), nullable=True),
    sa.Column('numOfBath', sa.String(length=30), nullable=True),
    sa.Column('pric', sa.String(length=80), nullable=True),
    sa.Column('proptype', sa.String(length=29), nullable=True),
    sa.Column('location', sa.String(length=225), nullable=True),
    sa.Column('pic', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
