"""empty message

Revision ID: c279fcd8abec
Revises: 
Create Date: 2021-03-17 20:21:52.371897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c279fcd8abec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('numOfBed', sa.String(length=80), nullable=True),
    sa.Column('numOfBath', sa.String(length=30), nullable=True),
    sa.Column('pric', sa.String(length=80), nullable=True),
    sa.Column('proptype', sa.String(length=29), nullable=True),
    sa.Column('location', sa.String(length=225), nullable=True),
    sa.Column('photo_name', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_property_photo_name'), 'user_property', ['photo_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_property_photo_name'), table_name='user_property')
    op.drop_table('user_property')
    # ### end Alembic commands ###
